### ISSUE TITLE
Extend possible parameter values with string type

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-core#11]
Hello fellow martians,

Wouldn't it be great if parameters in archives could also hold (at least) string values rather than exclusively numeric values? For instance, it would facilitate storage of experimental details in metadata parameters which can easily be read by scripts later on.

What do you guys think?

**Comment by karlduderstadt** [comment]
Hi @mjosch I think this is a great idea and we should add it! For now I would propose adding string so you can add experimental details, like buffers etc.. 

We could add booleans and other field types, but My feeling is that string and numbers should cover most requirements without add too much additional complexity. 

So the method setStringParamter and getStringParameter etc.. will be added to MarsMetadata and Molecule records here in mars-core and an additional tab will be added to mars-fx to display string fields and allow adding editing. Does this sound reasonable?

**Comment by karlduderstadt** [comment]
Maybe it is worth noting with with OME Metadata records string and number fields can be added to Images and planes. However, these can only be edited in scripts and not in the gui and are not as global as your proposal. Also, nothing is available for Molecules currently for strings.

**Comment by mjosch** [comment]
Hi @karlduderstadt I think adding StringParameters should be sufficient as they give plenty of flexibility - so that sounds perfect. 
Looking forward to the release!

**Comment by karlduderstadt** [comment]
Hi @mjosch Thanks for this suggestion! Now mars supports double, string, and boolean parameters types within the following commits - 68f897c and 6331605

Support has also been added to mars-fx so they type of a parameter can be chosen and checkboxes appear for boolean parameters.

I think this is now addressed, so I am going to close this issue.
