### ISSUE TITLE
Connection with TrackMate seems broken 

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#12]
<img width="1213" alt="Screenshot 2020-10-01 at 15 57 55" src="https://user-images.githubusercontent.com/61824826/94819144-3410eb80-03ff-11eb-9767-7e0706ac72e6.png">

When tracking via TrackMate the following error is raised upon exporting the data to Mars. Could you please take a look what is going wrong?

**Comment by karlduderstadt** [comment]
Ahh I changed that method to setImageID( in mars-core-1.0.0-beta-8 and didn't update the mars-trackmate jar. So now I fixed that and uploaded the new version of mars-trackmate to the update site. Please let me know if that fixes the problem.

**Comment by NadiaHuisjes** [comment]
The issue is resolved. Thank you!
