### ISSUE TITLE
Suggested upgrade: make the preview ROI circle indicators yellow

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#18]
When working with the circle indicator I noticed that especially on red/green data it is difficult to see the circle indicators. Perhaps it would be better to make them yellow so they stand out more?

**Comment by karlduderstadt** [comment]
Ahh that makes sense. Good suggestion!

Do you think we should just switch to yellow or provide a ratio button with a couple options? The color we have currently is really nice on black.

Somehow related. Do you have any suggestions about which input should control the diameter of the preview circle. Currently, it is the fit radius. But it could instead be the inner radius for integration... 

Or should we add integration preview as an option in addition to circle and cross...

**Comment by NadiaHuisjes** [comment]
I am not sure. Having multiple options could be nice when dealing with differently coloured data (and perhaps also for people with difficulties discriminating certain colors). But it does make the dialog a bit more crowded.

I think to me coupling it to the integration settings would be most intuitive (and then it also can remain the same between the peak finder and molecule integrator tools and would not need an addition).

**Comment by karlduderstadt** [comment]
At the moment there is no preview mode in the molecule integrator. The preview mode is only available in the TransformROIsCommand. in that case there is no setting for the integration radius, so I have to think about how best to add this in that context. I think we should create a separate issue for that.
