### ISSUE TITLE
PeakFitter-Tracker ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-core#2]
Dear fellow Martians,

Lately, I keep encountering the error below when using either PeakFitter or PeakTracker. Unfortunately, the exception does not always occur with the same settings on the same image - a bit puzzling.

<img width="1013" alt="Peak Tracker ArrayOutOfBounds" src="https://user-images.githubusercontent.com/17951396/79537938-9eb5b100-8083-11ea-8709-0fa84c5a0ee0.png">

**Comment by karlduderstadt** [comment]
Hi @mjosch,

Thanks for reporting this issue. I have attempted to reproduce the error without success. It is not entirely clear to me what could be causing this ArrayIndexOurOfBoundsException, but the error occurs during the initial Peak Finding and Fitting process prior to Tracking, which explains why it occurs for both tools.

I will keep trying different videos and testing. If you happen to find a reliable method to reproduce this error, but come back and post it here. I am sure we can solve this issue.

**Comment by karlduderstadt** [comment]
I haven't see this issue come up in a long time and there have been large updates to the Peak Tracker, so I am going to close this issue for now.
