### ISSUE TITLE
"Keep Originals" checkbox in Overlay Channels command does not trigger

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-core#4]
Hi @karlduderstadt,

I just noticed a minor flaw in the Overlay Channels command. The "keep originals" checkbox doesn't seem to trigger for me. Regardless of the selection, the original images always stay open. 
Do you also encounter this problem?

**Comment by mjosch** [comment]
Update: It seems like the original is actually only still kept open in Fiji GUI (the window itself). However, when trying to perform actions on the original it throws errors that the original does not exist. I hope this helps

**Comment by karlduderstadt** [comment]
Thanks for the update about this issue. It is a bit of a puzzle for me. An imagej command actually does the overlay and takes the boolean to set / unset keep originals. In line 205 of OverlayChannelsCommand:
```
imgOut = ij.plugin.RGBStackMerge.mergeChannels(images, keep);
```
So I wonder why this is not working. Perhaps I don't understand the use. I believe the keep variable is set correctly, but I will check. I will investigate further and get back to you.

**Comment by karlduderstadt** [comment]
Ahhh I guess the images in the above line are generated and never displayed directly so we could just set keep to false. Always.

Do you need it to close the other images automatically. I think in this case, we would then need to add some lines that close them OR we could remove the checkbox :)

What do you think would be best?

**Comment by mjosch** [comment]
Exactly, I figured it is simply using imagej's mergeChannels command so I don't understand the different behavior in OverlayChannelsCommand.
I'm not sure whether keeping or closing the original images is the preferred setting but I think removing the checkbox is a good idea.

**Comment by karlduderstadt** [comment]
Ok I removed the checkbox option, so I guess this "fixes" the problem. 

In the process of implementing this fix, I noticed that if SCIFIO is turned on duplicate image entries show up in the ChoiceBoxes. I wrote a version that fixes this and works well with SCIFIO, but then I found this version is broken with SCIFIO turned off, which is the current way to work with mars...

So this is a bit of a puzzle. The migration to OME will probably require the SCIFIO version, so I guess when we make that switch I will also change to the SCIFIO compatible version and at that point there will be no going back. 

Can you at least confirm this is working for now?

**Comment by karlduderstadt** [comment]
The latest commit implements a work around that simply closes the individual images if the keep option is false. @mjosch - does this address the issue?

**Comment by mjosch** [comment]
I tested the newest version and images are properly closed now when keep is set to false. Also, it behaves as expected if the originals are kept. So I don't see any more issues with the command, I'll close the issue
Thanks a lot @karlduderstadt, I'm glad we could fix it!
