### ISSUE TITLE
Issues with commit c9b90df (msd vs variance references)

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-core#5]
Hello Martians,

The recent renaming of MSD to the correct label variance seems not fully implemented in all commands yet. I just encountered a major bug in the DNA finder command. It is still referencing to MSD for filtering but the new filter must reference to variance. Unfortunately turning off the filter doesn't allow to run DNA finder at this moment. This problem might also occur in other commands using MSD.

<img width="957" alt="Bildschirmfoto 2020-05-16 um 12 06 02" src="https://user-images.githubusercontent.com/39280948/82117158-ba89a100-976e-11ea-864c-92c7f45713f5.png">

**Comment by karlduderstadt** [comment]
Hi @mjosch,

Thanks for reporting this problem. The DNAFinder is actually in mars-commands, not mars-core, so I will close the issue here and fix it over there. Indeed this was a big oversight on my part to not also check that mars-commands still works.
