### ISSUE TITLE
Set/Get parameters in KCP tools

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#6]
Hi Karl, 
I noticed that some set/get parameter functions are missing for the KCP tools. Can you add them? 

* Change point finder:
- Region source
- Calculate from background
- Analyze region
- Region
- Include
- Tags (comma separated list)

* Single change point finder:
- Position name
- Include
- Tags (comma separated list)

apart from these, the script allows for setting more parameters than the dialogue gives the options for...
- Fit steps
- Global sigma
- Confidence level

* Segment Distribution Builder
Since we decided to change this, I did not add it to this overview.

* Sigma Calculator - all parameters
- MoleculeArchive
- XColumn
- YColumn
- Region
- from
- to
- Region from MarsRecord

**Comment by karlduderstadt** [comment]
Ahh great that you noticed this. I have made the changes. Now everything should show up in the log and all getters and setters are implemented. I am closing this issue for now, but please reopen if you think it is not fully addressed

**Comment by NadiaHuisjes** [comment]
Hi Karl,
I checked the three remaining KCP functions. ChangePointFinderCommand is fine now. However, SigmaCalculator does not have any get or set functions anymore now, and also SingleChangePointFinder was not updated/did not improve. Can you please take a look at this again? Maybe it is just the java docs that did not update?

**Comment by karlduderstadt** [comment]
Ok I think it is address by several more commits. Can you check and test all the options and if everything is ok, we can close this issue (again).

**Comment by karlduderstadt** [comment]
Most updates were for the Single Change Point detector in commit b3b1a993

**Comment by NadiaHuisjes** [comment]
All functions are in there now! Thank you!
